---
- hosts: localhost
  user: jfdufour
  connection: local

  vars_files:
    - vars/main.yml
    - vars/personal_info.yml

  roles: []

  tasks:
    - name: Upgrade all homebrew packages
      homebrew: update_homebrew=yes upgrade_all=yes

    - name: Install homebrew packages
      homebrew:
        name: "{{ item.name | default(item) }}"
        install_options: "{{ item.install_options | default(omit) }}"
        state: "{{ item.state | default('present') }}"
      loop: "{{ homebrew_installed_packages }}"

    - name: Install configured cask applications.
      homebrew_cask:
        name: "{{ item.name | default(item) }}"
        state: present
        install_options: "{{ item.install_options | default('appdir=' + homebrew_cask_appdir) }}"
        sudo_password: "{{ ansible_become_pass | default(omit) }}"
      loop: "{{ homebrew_cask_apps }}"

    # - include: tasks/dmg-install.yml appName="handyPrint" dmgURL=https://s3.amazonaws.com/netputing/handyPrint/handyPrint+v5.5.0.dmg

    - import_tasks: tasks/sublimetext.yml

    - import_tasks: tasks/apps_associations.yml

    - import_tasks: tasks/dotfiles/dotfiles.yml

    - import_tasks: tasks/java.yml

    - import_tasks: tasks/git.yml

    - import_tasks: tasks/finder.yml

    - import_tasks: tasks/ssh.yml

    # - import_tasks: tasks/gickup.yml

    # - import_tasks: tasks/dock/dock.yml

    
