---
- hosts: localhost
  user: jfdufour
  connection: local

  vars_files:
    - vars/main.yml
    - vars/personal_info.yml

  roles: []

  tasks:
    - name: Upgrade all homebrew packages
      homebrew: update_homebrew=yes upgrade_all=yes

    - name: Install homebrew packages
      homebrew:
        name: "{{ item.name | default(item) }}"
        install_options: "{{ item.install_options | default(omit) }}"
        state: "{{ item.state | default('present') }}"
      loop: "{{ homebrew_installed_packages }}"

    - name: Install configured cask applications.
      homebrew_cask:
        name: "{{ item.name | default(item) }}"
        state: present
        install_options: "{{ item.install_options | default('appdir=' + homebrew_cask_appdir) }}"
        sudo_password: "{{ ansible_become_pass | default(omit) }}"
      loop: "{{ homebrew_cask_apps }}"

    - import_tasks: tasks/sublimetext.yml

    - include: tasks/zip-install.yml appName="iStat Menus.app" dmgURL=https://cdn.bjango.com/files/istatmenus6/istatmenus6.61.zip

    - include: tasks/zip-install.yml appName="apache-maven-3.8.4" dmgURL=https://dlcdn.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.zip

    - include: tasks/dmg-install.yml appName="balenaEtcher" dmgURL=https://github.com/balena-io/etcher/releases/download/v1.7.1/balenaEtcher-1.7.1.dmg

    - include: tasks/dmg-install.yml appName="Google Chrome" dmgURL=https://dl.google.com/chrome/mac/universal/stable/GGRO/googlechrome.dmg

    - include: tasks/zip-install.yml appName="Screens 4.app" dmgURL=https://updates.edovia.com/com.edovia.screens4.mac/Screens_4.9.1b1637346403.zip

    - include: tasks/zip-install.yml appName="Transmit.app" dmgURL=https://download-keycdn.panic.com/transmit/Transmit%205.8.2.zip

    - import_tasks: tasks/apps_associations.yml

    - import_tasks: tasks/dotfiles/dotfiles.yml

    - import_tasks: tasks/java.yml

    - import_tasks: tasks/git.yml

    - import_tasks: tasks/finder.yml

    - import_tasks: tasks/dock/dock.yml

    