---
- hosts: localhost
  user: jfdufour
  connection: local

  vars_files:
    - vars/main.yml

  roles: []

  tasks:
    - name: Upgrade all homebrew packages
      homebrew: update_homebrew=yes upgrade_all=yes
      tags: ['always']

    - name: Install homebrew packages
      homebrew:
        name: "{{ item.name | default(item) }}"
        install_options: "{{ item.install_options | default(omit) }}"
        state: "{{ item.state | default('present') }}"
      loop: "{{ homebrew_installed_packages }}"
      tags: ['always']

    - import_tasks: tasks/sublimetext.yml
      tags: ['always']

    - include: tasks/zip-install.yml appName="iStat Menus.app" dmgURL=https://cdn.bjango.com/files/istatmenus6/istatmenus6.61.zip
      tags: ['always']

    - include: tasks/zip-install.yml appName="apache-maven-3.8.4" dmgURL=https://dlcdn.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.zip
      tags: ['always']

    - include: tasks/dmg-install.yml appName="IntelliJ IDEA" dmgURL=https://download.jetbrains.com/idea/ideaIU-2021.3-aarch64.dmg
      tags: ['work']

    - include: tasks/dmg-install.yml appName="Viscosity" dmgURL=https://www.sparklabs.com/downloads/Viscosity.dmg
      tags: ['work']

    - include: tasks/dmg-install.yml appName="TablePlus" dmgURL=https://download.tableplus.com/macos/396/TablePlus.dmg
      tags: ['work']

    - name: Copy dotfiles into home folder.
      command: cp dotfiles/{{ item }} {{ dotfiles_home }}/{{ item }}
      become: false
      with_items: "{{ dotfiles_files }}"
      tags: ['always']

    - name: Check file type association
      command: "duti -s {{ item.0.bundle_id }} {{ item.1 }} all"
      with_subelements:
        - "{{ default_apps_associations }}"
        - utis
      tags: ['always']

    - import_tasks: tasks/finder.yml

    