---
- hosts: localhost
  user: jfdufour
  connection: local

  vars_files:
    - vars/main.yml

  roles: []

  tasks:
    - name: Upgrade all homebrew packages
      homebrew: update_homebrew=yes upgrade_all=yes
      tags: ['always']

    - name: Install homebrew packages
      homebrew:
        name: "{{ item.name | default(item) }}"
        install_options: "{{ item.install_options | default(omit) }}"
        state: "{{ item.state | default('present') }}"
      loop: "{{ homebrew_installed_packages }}"
      tags: ['always']

    - import_tasks: tasks/sublimetext.yml
      tags: ['always']

    - name: Copy dotfiles into home folder.
      command: cp dotfiles/{{ item }} {{ dotfiles_home }}/{{ item }}
      become: false
      with_items: "{{ dotfiles_files }}"
      tags: ['always']

    - name: Check file type association
      command: "duti -s {{ item.0.bundle_id }} {{ item.1 }} all"
      with_subelements:
        - "{{ default_apps_associations }}"
        - utis
      tags: ['always']

    - name: Finder default settings
      command: /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy name" ~/Library/Preferences/com.apple.finder.plist
      tags: ['always']

    - name: Restart finder
      command: killall Finder
      tags: ['always']