---
- name: "Check if finder default sorting is by name"
  ansible.builtin.command: /usr/libexec/PlistBuddy -c "Print :StandardViewSettings:IconViewSettings:arrangeBy" ~/Library/Preferences/com.apple.finder.plist
  register: findersort_value
  changed_when: false
  failed_when: false

- name: Finder default sort
  command: /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy name" ~/Library/Preferences/com.apple.finder.plist
  when: findersort_value.stdout != 'name'
  register: findersort_result

- name: "Check if finder default sorting is by name"
  ansible.builtin.command: defaults read com.apple.finder NewWindowTargetPath
  register: findertarget_value
  changed_when: false
  failed_when: false

- name: Finder default folder
  command: defaults write com.apple.finder NewWindowTargetPath -string "file://localhost/Applications"
  when: findertarget_value.stdout != 'file://localhost/Applications'
  register: findertarget_result

- name: Restart finder
  command: killall Finder
  when: findersort_result.skipped == False or findertarget_result.skipped == False
  