---
- name: Finder default sort
  command: /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy name" ~/Library/Preferences/com.apple.finder.plist
  tags: ['always']

- name: Finder default folder
  command: defaults write com.apple.finder NewWindowTargetPath -string "file://localhost/Applications"
  tags: ['always']

- name: Restart finder
  command: killall Finder
  tags: ['always']