---
- name: "Check if git user.name is defined"
  ansible.builtin.command: "git config --global user.name"
  register: gitname_exists
  changed_when: false

- name: Setup git user.name
  command: git config --global --replace-all user.name '{{ full_name }}'
  when: gitname_exists.rc >0 or gitname_exists.stdout != full_name

- name: "Check if git user.email is defined"
  ansible.builtin.command: "git config --global user.email"
  register: gitemail_exists
  changed_when: false

- name: Setup git user.email
  command: git config --global --replace-all user.email  {{ email }}
  when: gitemail_exists.rc >0 or gitemail_exists.stdout != email

- name: "Check if git pull.rebase is defined"
  ansible.builtin.command: "git config --global pull.rebase"
  register: gitpull_exists
  changed_when: false

- name: Setup git pull.rebase
  command: git config --global --replace-all pull.rebase true
  when: gitpull_exists.rc >0 or gitpull_exists.stdout != 'true'
