---
- include: tasks/targz-install.yml appName="jdk-17.jdk" dmgURL=https://download.oracle.com/java/17/latest/jdk-17_macos-x64_bin.tar.gz

- local_action: stat path='/Library/Java/JavaVirtualMachines/jdk-17.jdk'
  register: java_link_exists

- name: Add jdk-17.jdk to JavaVirtualMachines
  command: ln -sfn /Applications/jdk-17.jdk /Library/Java/JavaVirtualMachines/jdk-17.jdk
  when: java_link_exists.stat.exists == False
  become: true
